3-example-component/config/routes.rb
Example3Component::Application.routes.draw do
  get "demo/show"
  get "demo/get_data", :via => :get, :as => "get_data"

end

3-example-component/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

3-example-component/app/controllers/demo_controller.rb
# encoding: utf-8
class DemoController < ApplicationController
  def show
  end
  
  def get_data
    fake_data = [
      "Adamov",
      "Albrechtice",
      "Benešov",
      "Bernartice", 
      "Chářovice",
      "Chleby"
    ]
    
    response = fake_data.select {|city| city.downcase.match(/^#{params[:query].downcase}/)} unless params[:query].blank?
    respond_to do |format|
      format.json { render :json => (response || []).to_json, :status => :ok }
    end
  end
end

3-example-component/app/helpers/application_helper.rb
module ApplicationHelper
end

3-example-component/app/helpers/demo_helper.rb
module DemoHelper
end

3-example-component/app/views/demo/show.html.erb
<h1>Autocomplete time!</h1>

<%= form_tag(get_data_path, {:class => "form"}) do %>
    <%= label_tag :city, "Město" %>
    <%= text_field_tag :city, nil, {"data-url" => get_data_path} %>
<% end -%>

3-example-component/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Example3Component</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>